/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/n1eGgjok9Ia
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Sheet, SheetTrigger, SheetContent, SheetClose } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"

export function drawer() {
  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="outline">Open Drawer</Button>
      </SheetTrigger>
      <SheetContent side="right" className="w-[400px] bg-background shadow-lg">
        <div className="flex h-full flex-col">
          <div className="flex items-center justify-between border-b px-6 py-4">
            <h3 className="text-lg font-semibold">Comments</h3>
            <SheetClose asChild>
              <Button variant="ghost" size="icon">
                <XIcon className="h-5 w-5" />
              </Button>
            </SheetClose>
          </div>
          <div className="p-6 space-y-6">
            <div className="flex items-start gap-4">
              <Avatar className="w-10 h-10 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="grid gap-2 flex-1">
                <div className="flex items-center gap-2">
                  <div className="font-semibold">John Doe</div>
                  <div className="text-xs text-muted-foreground">2 hours ago</div>
                </div>
                <div className="flex items-center gap-4">
                  <div className="flex-1">
                    <Textarea placeholder="Write your comment..." className="resize-none" />
                  </div>
                  <div className="flex gap-2">
                    <Button variant="ghost">Cancel</Button>
                    <Button>Respond</Button>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="w-10 h-10 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="grid gap-2">
                <div className="flex items-center gap-2">
                  <div className="font-semibold">Jane Smith</div>
                  <div className="text-xs text-muted-foreground">1 day ago</div>
                </div>
                <div>I agree, the design is really sleek and modern.</div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="w-10 h-10 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="grid gap-2">
                <div className="flex items-center gap-2">
                  <div className="font-semibold">Michael Johnson</div>
                  <div className="text-xs text-muted-foreground">3 days ago</div>
                </div>
                <div>I'm excited to try this out. The features look really useful.</div>
              </div>
            </div>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  )
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
